config/routes.rb
Project4::Application.routes.draw do

  root  'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

  
  resources :users do
    collection do
      get 'login'
      post 'post_login'
      get 'logout'
      get 'search'
    end
    resources :photos do 
      resources :tags,  only:  [:new, :create]
      resources :comments
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
  default_scope -> { order('date_time ASC') }

  validates :comment, presence: true, length: { maximum: 140 }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many   :comment
  has_many   :tag
  default_scope -> { order('date_time DESC') }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photo
  has_many :comment

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :login, presence: true, uniqueness: { case_sensitive: false }
  
  def password_valid?(candidate_password)
  	self.password_digest == User.encrypt(candidate_password + self.salt.to_s)
  end

  def User.encrypt(token)
  	Digest::SHA1.hexdigest(token.to_s)
  end

  def password
  	self.password_digest
  end

  def password=(password)
	self.salt = Random.new.rand(1..(1<<31))
	self.password_digest = User.encrypt(password + self.salt.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UsersHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action  :signed_in_user, only: [:new, :create, :update]

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comment.build
  end
  def create
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.new(date_time: Time.now.strftime("%Y-%m-%d %H:%M:%S"), comment: params[:comment][:comment], photo_id: params[:photo_id], user_id: session[:user_id])
    if @comment.valid?
      @comment.save
      redirect_to user_photos_path(@user)
    else
      render 'new'
    end
  end
  def update
    @user = User.find(params[:user_id])
    redirect_to user_photos_path(@user)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action  :signed_in_user, only: [:new, :create]

  def index
    @user = User.find(params[:user_id])
  end
  def new
    @user = User.find(params[:user_id])
    @photo = @user.photo.build
  end
  def create
    @user = User.find(params[:user_id])
    if !params[:photo]
      flash[:error] = "No file selected!"
      redirect_to new_user_photo_path(@user)
      return
    end
    uploaded = params[:photo][:picture]
    File.open(Rails.root.join('public', 'images', uploaded.original_filename), 'wb') do |file|
      file.write(uploaded.read)
    end
    @user.photo.create(date_time: Time.now, file_name: uploaded.original_filename)
    redirect_to user_photos_path(@user)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if session[:user_id]
      redirect_to user_photos_path(User.find_by_id(session[:user_id]))
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    user = User.find(params[:user_id])
    photo = Photo.find(params[:photo_id])
    sel_user = User.find(params[:sel])
    xloc = params[:xloc]
    yloc = params[:yloc]
    width = params[:width]
    height = params[:height]
    if xloc.empty? || yloc.empty? || width.empty? || height.empty?
      flash[:error] = "no tag found"
    else
      photo.tag.create(photo_id: photo.id, xloc: xloc.to_i, yloc: yloc.to_i, width: width.to_i, height: height.to_i, user_name: sel_user.first_name + " " + sel_user.last_name)
    end
    redirect_to user_photos_path(user) + "#" + photo.file_name

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def login
  end

  def index
    @users = User.all
  end

  def post_login
    @usr = User.find_by_login(params[:login_form][:login_name])
    if (@usr == nil)
      flash.now[:error] = 'Invalid user!'
      render 'login'
    elsif @usr.password_valid?(params[:login_form][:password])
      session[:user_id] = @usr.id
      redirect_to user_photos_path(@usr.id)
    else
      flash.now[:error] = 'Invalid password'
      render 'login'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    @user = User.new(user_params)
    if !@user.valid?
      render 'new'
      return
    end
    if params[:user][:password].empty?
      flash.now[:error] = 'password cannot be empty'
      render 'new'
    elsif params[:user][:password] != params[:user][:password_confirmation]
      flash.now[:error] = "password and confirmation don't match"
      render 'new'
    else
      @user.password = params[:user][:password]
      if @user.save
        redirect_to login_users_path
      else
        render 'new'
      end
    end

  end

  def new
    @user = User.new
  end

  def search
    txt = params[:query]
    photos = Photo.all
    @match = []
    if !txt.empty?
      txt = txt.downcase
      for photo in photos
        for comment in photo.comment
          if comment.comment.downcase.include? txt
            @match.push(photo)
            break
          end
        end
        if not @match.include? photo
          for tag in photo.tag
            if tag.user_name.downcase.include? txt
              @match.push(photo)
              break
            end
          end
        end
      end
    end
    render partial: 'search'
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :login)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Smart Blog"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def signed_in_user
    redirect_to login_users_path unless session[:user_id]
  end
end

app/views/comments/_comment_form.html.erb
<%= form_for([@user, @photo, @comment]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.text_area :comment, placeholder: "Type your comments" %>
</br>
  <%= f.submit "Submit", class: "btn btn-primary" %><%= link_to "Cancel", user_photos_path(@user), class: "btn btn-info offset1" %>
<% end %>

app/views/comments/new.html.erb
<% provide(:title, "New comment") %>
<h1>Create new comment</h1>
<%= render 'shared/photo', photo: @photo %>
<%= render 'comment_form' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class="text-center"> Copyright © 2014 Welcome to little fire's blog </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Smart Blog", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if session[:user_id]==nil %>
            <li><%= link_to "Login", login_users_path %></li>
            <li><%= link_to "Register now", new_user_path %></li>
            <li><%= link_to "Users", users_path %></li>
          <% else %>
            <li><a href="#" id="welcome">Hello <%= User.find(session[:user_id]).last_name %>!</a></li>
            <li><%= link_to "Home", user_photos_path(session[:user_id]) %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Logout", "/users/logout" %></li>
          <% end %> 
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% if flash[:error] %>
      <div class="alert">
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>

</html>

app/views/photos/index.html.erb
<% provide(:title, @user.first_name + " " + @user.last_name) %>
<h1><%= @user.first_name %> <%= @user.last_name %> </h1>
<% if session[:user_id] == @user.id %>
<p><%= link_to "Post new photos", new_user_photo_path(@user) %></p>
<% end %>
  <% @user.photo.each do |photo| %>
    <%= render 'shared/photo', photo: photo %>
  <% end %>

app/views/photos/new.html.erb
<% provide(:title, "Post new photo") %>
<h1>Post new photo</h1>
<div class="offset4">
  <%= form_for([@user,@photo]) do |f| %>
    <p><%= f.file_field :picture, class: "fileUpload" %></p>
    <p><%= f.submit "Submit", class: "btn btn-primary" %><%= link_to 'Cancel', user_photos_path, class: "btn btn-info offset1" %></p>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="alert alert-danger">
  <% object.errors.full_messages.each do |msg|%>
    <li> <%= msg %> </li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_photo.html.erb
<div class="photo-container" id="photo-<%= photo.id %>">  
  <%= image_tag "/images/#{photo.file_name}", alt: photo.file_name, id: photo.file_name %>
  <div class="tag-box" id="tag-<%= photo.id %>"></div>
  <% photo.tag.each do |tag| %>
    <% if tag.xloc %>
      <div class="tag-show" style="left: <%= tag.xloc.to_s + "px" %>; top: <%= tag.yloc.to_s + "px" %>; width: <%= tag.width.to_s + "px" %>; height: <%= tag.height.to_s + "px" %>" title="<%= tag.user_name %>">
      </div> 
    <% end %>
  <% end %>
</div>
<h2>Post time <%= photo.date_time %></h2>
<% if session[:user_id] %>
  <%= form_tag(action: "create", controller: "tags", photo_id: photo.id) do %>
    <input type="button" value="Tag photo" onclick="new Tagger('photo-<%= photo.id %>', 'tag-<%= photo.id %>', this.form.sel, this.form.submit, this.form.xloc, this.form.yloc, this.form.width, this.form.height).drag();"/>
    <select name="sel" class="tag-form">
      <%= options_from_collection_for_select(User.all, :id, :first_name) %>
    </select>
    <input type="submit" name="submit" value="Confirm tagging" class="tag-form" />
    <input type="hidden" name="xloc" />
    <input type="hidden" name="yloc" />
    <input type="hidden" name="width" />
    <input type="hidden" name="height" />
  <% end %>
<% end %>
<ul class="comment-list">
  <% photo.comment.each do |comment| %>
    <% if comment.user %>
      <li><div class="comment"><%= link_to comment.user.first_name + " " + comment.user.last_name, user_photos_path(comment.user) %>: <%= comment.comment %></div> 
        <div class="timestamp"><%= comment.date_time %></div>
      </li>
    <% end %>
  <% end %>
</ul>
<% if session[:user_id] %>
  <p><%= link_to "New comment", new_user_photo_comment_path(@user,photo) %></p>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="cv">
<h1>About Little Fire</h1>

<p>Little Fire means energetic and enthusiastic young man. Interested in my background? This is the right place. </p>

<h3>Education</h3>

<ul>
  <li>08/2009-12/2011    MS in EE, North Carolina State University, GPA: 3.72</li>
   <li>09/2003-07/2007    BS in EE, Zhejiang University, China, GPA: 3.86</li>
</ul>

<h3>Software Skills</h3>

 <ul>
   <li>Proficient in Java, data structures and algorithms</li>
   <li>Experience in Perl, Python, shell scripting and LINUX utilities grep / sed etc</li>
   <li>Experience in HTML, CSS, JavaScript, Ruby on Rails</li>
 </ul>

<h3>Work Experience</h3>

<h4><span class="timeline">01/2012-present</span>   Design Engineer @ ARM  –  San Jose, CA</h4>

<ul>
  <li>Register file SRAM CMOS circuit design and verification</li>
  <li>Perl/Python scripting for data extraction, formatting and reporting</li>
    <ol>
      <li>Data extraction and reporting automation in <strong>Perl</strong></li>
      <li>Early stage circuit leakage problem analysis in <strong>Perl</strong></li>
      <li>Verilog infrastructure development in <strong>Perl</strong></li>
      <li>Verilog spec generator in <strong>Python</strong></li>
    </ol>
</ul>

<h3>Stanford Open Course Projects</h3>

<h4><span class="timeline">06/2013-12/2013</span>   Web Application in Ruby on Rails - CS142</h4>

<ul>
  <li>Photo posting blog website development with Ruby on Rails</li>
  <li><strong>Core features:</strong></li>
    <ol>
      <li>User registration, login and logout</li>
      <li>Photo upload and comments posting</li>
      <li>Photo tagging with JavaScript ( only available to logged in users )</li>
      <li>Photo search with JavaScript and AJAX</li>
    </ol>
  <li><a href="http://littlefire.herokuapp.com/">http://littlefire.herokuapp.com/</a></li>
  <li><a href="https://github.com/ywang28/smart_blog">https://github.com/ywang28/smart_blog</a></li>
</ul>

<h4><span class="timeline">04/2013-05/2013</span>   Programming Methodology in Java - CS106A</h4>
<ul>
  <li>Basic Breakout game with fixed size paddle and 5 levels of bricks</li>
  <li>Hangman. Popular word guess game with guess word recording and hangman drawing</li>
  <li>Yahtzee game supporting up to 4 players and 13 score categories with score board</li>
  <li>All the games are using Stanford acm graphics library</li>
</ul>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "contact") %>
<h1>Contact</h1>
<p>
  The Smart Blog is developed based on Stanford open course project <a href="http://www.stanford.edu/~ouster/cgi-bin/cs142-spring13/projects.php">CS142: Web Applications</a>.

  Some great ideas are learned from <a href="http://www.railstutorial.org/book">Ruby on Rails Tutorial</a>.
</p>
<p>
  If you have more questions, please contact Yalin at this email 
  <a href = "mailto: ywang28@ncsu.edu">ywang28@ncsu.edu</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "home") %>
<div class="center hero-unit">
  <h1>Welcome to the Smart Blog</h1>

  <h2>
    Welcome to littlefire's home page
  </h2>

  <%= link_to "Sign up now!", new_user_path,
                                class: "btn btn-large btn-primary" %>
   <%= link_to "View as guest user", users_path,
                                class: "btn btn-large btn-primary" %>                               
</div>

app/views/users/_search.html.erb
<% for photo in @match %>
  <%= link_to image_tag("/images/#{photo.file_name}", alt: photo.file_name, class: "thumb-nail"), user_photos_path(photo.user) + "#" + photo.file_name %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<h1>Users</h1>
<form>
  <label>Enter key words to search photos (case insensitive):</label>
  <input type="text" name="photo-search" placeholder="barack" oninput="new AutoSearch(this.value, '/users/search', 'query', 'show-photo').search();" />
</form>
<div id="show-photo"></div>
<ul class="users">
<% @users.each do |u| %>
  <li><%=link_to u.first_name+" "+u.last_name, user_photos_path(u) %></li>
<% end %>
</ul>

app/views/users/login.html.erb
<% provide(:title, "Sign in") %>
<h1>User login</h1>
<div class="row">
  <div class="span6 offset4">
    <%= form_for(:login_form, method: :post, url: post_login_users_path) do |f| %>

      <%= f.label :login_name %>
      <%= f.text_field :login_name %>

      <%= f.label :password %>
      <%= f.password_field :password %>
      </br>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>
    <p>New user? <%= link_to "Register now!", new_user_path %></p>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Register user</h1>
<div class="row">
  <div class="span6 offset4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :login %>
      <%= f.text_field :login %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <br></br>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>